name: fetch_tray_cache_plugin
description: A caching plugin for fetch_tray.
version: 0.0.4
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  fetch_tray: ^0.3.3
  dio: ^5.2.1+1
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  logger: ^2.0.2+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
